const labelsTable = [
    "Font",
    "Art",
    "Circle",
    "Graphics",
    "Illustration",
    "Handwriting",
    "Logo",
    "Label",
    "Graphic design",
    "Signage",
    "Wall",
    "Poster",
    "Visual arts",
    "Graffiti",
    "Advertising",
    "Paint",
    "Publication",
    "Paper",
    "Design",
    "Azure",
    "Electric blue",
    "Brand",
    "Symbol",
    "Event",
    "Sleeve",
    "Cool",
    "Thigh",
    "Hat",
    "Cap",
    "Motor vehicle",
    "Emblem",
    "Costume hat",
    "Textile",
    "Cartoon",
    "Rectangle",
    "T-shirt",
    "Fictional character",
    "Carmine",
    "Outerwear",
    "Dog",
    "White",
    "Black",
    "Standing",
    "Carnivore",
    "Painting",
    "Mural",
    "Drawing",
    "Artist",
    "Pattern",
    "Creative arts",
    "Gesture",
    "Pink",
    "Eyelash",
    "Comic book",
    "Animated cartoon",
    "Comics",
    "Tints and shades",
    "Ink",
    "Stencil",
    "Monochrome",
    "Dog breed",
    "Yellow",
    "Fawn",
    "Dog supply",
    "Companion dog",
    "Red",
    "Book",
    "Space",
    "Book cover",
    "Beard",
    "Facial hair",
    "Automotive tire",
    "Drink",
    "Bottle",
    "Nail",
    "Finger",
    "Alcoholic beverage",
    "Material property",
    "Glass bottle",
    "World",
    "Team",
    "Facade",
    "Magenta",
    "Street art",
    "Flower",
    "Natural foods",
    "Flower Arranging",
    "Floristry",
    "Floral design",
    "Recipe",
    "Ingredient",
    "Happy",
    "Hairstyle",
    "Vision care",
    "Sunglasses",
    "Eyewear",
    "Wood",
    "Fixture",
    "Tree",
    "Plant",
    "Metal",
    "Facial expression",
    "Fashion",
    "Sun hat",
    "Gas",
    "Automotive exterior",
    "Sign",
    "Doodle",
    "Urban design",
    "Musical instrument",
    "Guitar",
    "Guitar accessory",
    "String instrument accessory",
    "String instrument",
    "Musician",
    "Guitarist",
    "Road surface",
    "Line",
    "Asphalt",
    "Flooring",
    "Wrist",
    "Banner",
    "Public event",
    "Human",
    "Human body",
    "Organism",
    "Science",
    "City",
    "Working animal",
    "Snout",
    "Religious item",
    "Mythology",
    "History",
    "Landmark",
    "Product",
    "Headgear",
    "Security",
    "Workwear",
    "Personal protective equipment",
    "Blue",
    "Grass",
    "Purple",
    "Picture frame",
    "Vertebrate",
    "Mammal",
    "Road",
    "Fiction",
    "Collage",
    "Flesh",
    "Writing",
    "Signature",
    "Astronaut",
    "Face",
    "Head",
    "Landscape",
    "News",
    "No expression",
    "Style",
    "Fun",
    "Photo caption",
    "Entertainment",
    "Performing arts",
    "Dance",
    "Music",
    "Thumb",
    "Building",
    "Window",
    "Mythical creature",
    "Snapshot",
    "Supernatural creature",
    "Photomontage",
    "Snack",
    "Travel",
    "Room",
    "Selling",
    "Linens",
    "Forehead",
    "Jaw",
    "Catwoman",
    "Screenshot",
    "Human anatomy",
    "Mouth",
    "Photograph",
    "Skull",
    "Fashion accessory",
    "Knee",
    "Squad",
    "Military uniform",
    "Military person",
    "Crew",
    "Non-commissioned officer",
    "Soldier",
    "Suit",
    "Street",
    "Trunk",
    "Cylinder",
    "Blackboard",
    "Triangle",
    "Electronic instrument",
    "Vintage advertisement",
    "Doll",
    "Fur",
    "Sculpture",
    "Moustache",
    "Brick",
    "Grey",
    "Heart",
    "Nose",
    "Cheek",
    "Kiss",
    "Shoe",
    "Leg",
    "Human leg",
    "Shorts",
    "Sandal",
    "Vintage clothing",
    "Bicycle",
    "Wheel",
    "Tire",
    "Bicycle wheel",
    "Bicycle tire",
    "Bicycle frame",
    "Bicycle fork",
    "Bicycle handlebar",
    "Art paint",
    "Watercolor paint",
    "Sidewalk",
    "Bird",
    "Green",
    "Liquid",
    "Collar",
    "Paper product",
    "Automotive design",
    "Brickwork",
    "Building material",
    "Amber",
    "Auto part",
    "Sportswear",
    "Temple",
    "Adaptation",
    "Whiskers",
    "Tail",
    "Organ",
    "Cat",
    "Black-and-white",
    "Tie",
    "Chin",
    "Eyebrow",
    "Eye",
    "Goggles",
    "Pest",
    "Waste container",
    "Terrestrial animal",
    "Orange",
    "Felidae",
    "Small to medium-sized cats",
    "Monochrome photography",
    "Watercraft",
    "Naval architecture",
    "Number",
    "Parallel",
    "Symmetry",
    "Document",
    "Cemetery",
    "Line art",
    "Hair",
    "Brown",
    "Hardwood",
    "People",
    "Glass",
    "Drinkware",
    "Concrete",
    "Coat",
    "White-collar worker",
    "Blazer",
    "Vehicle",
    "Car",
    "Chair",
    "Technology",
    "Engineering",
    "Machine",
    "Formal wear",
    "Flash photography",
    "Social group",
    "Slope",
    "Red hair",
    "Long hair",
    "Smile",
    "Collection",
    "Automotive decal",
    "Microphone",
    "Billboard",
    "Architecture",
    "Humour",
    "Printmaking",
    "Aqua",
    "Toy",
    "Dishware",
    "Sugar cake",
    "Cake decorating supply",
    "Crest",
    "Alcohol",
    "Sky",
    "Cloud",
    "Crowd",
    "Display device",
    "Soft drink",
    "Jersey",
    "Liver",
    "Reptile",
    "Newspaper",
    "Newsprint",
    "Hair coloring",
    "Bangs",
    "Public space",
    "Beer",
    "Petal",
    "Rose",
    "Wine",
    "Darkness",
    "Bone",
    "Fruit",
    "Food group",
    "Sports equipment",
    "Recreation",
    "Lip",
    "Neck",
    "Daytime",
    "Arthropod",
    "Insect",
    "Romance",
    "Morning",
    "Violet",
    "Emoticon",
    "Single-lens reflex camera",
    "Pollinator",
    "Leaf",
    "Moths and butterflies",
    "Square",
    "Sharing",
    "Soil",
    "Military camouflage",
    "Army",
    "Military organization",
    "Wrinkle",
    "Plucked string instruments",
    "Cake decorating",
    "Candle",
    "Santa claus",
    "Garden gnome",
    "Wildlife",
    "Beige",
    "Waist",
    "Lingerie",
    "Undergarment",
    "Black hair",
    "Extinction",
    "Fang",
    "Sporting Group",
    "Icing",
    "Sweetness",
    "Fence",
    "Human settlement",
    "Self-portrait",
    "Tower",
    "Badge",
    "Rolling",
    "Automotive wheel system",
    "Rim",
    "Audio equipment",
    "Automotive lighting",
    "Grave",
    "Urban area",
    "Calligraphy",
    "Stock photography",
    "Chalk",
    "Tar",
    "Kitchen utensil",
    "Heat",
    "Post-it note",
    "Infrastructure",
    "Liqueur",
    "Vest",
    "Hand",
    "Arm",
    "Peach",
    "Composite material",
    "Beak",
    "Horse",
    "Hybrid tea rose",
    "Revolver",
    "Flat panel display",
    "Electronic device",
    "Chest",
    "Cross",
    "Glasses",
    "Output device",
    "Elbow",
    "Collectable",
    "Balloon",
    "Bumper",
    "Sticker",
    "Botany",
    "Light",
    "Combat vehicle",
    "Tread",
    "Colorfulness",
    "Iris",
    "Terrestrial plant",
    "Nameplate",
    "Office supplies",
    "Shotgun",
    "Air gun",
    "Sea eagle",
    "Accipitridae",
    "Eagle",
    "Door",
    "Performance art",
    "Dress",
    "Fan",
    "Leisure",
    "Lighting",
    "Multimedia",
    "Artifact",
    "Science book",
    "Bag",
    "Hood",
    "Gas mask",
    "Sports gear",
    "Shooting",
    "Helmet",
    "People in nature",
    "Teenage mutant ninja turtles",
    "Gun barrel",
    "Street sign",
    "Pack animal",
    "Plant community",
    "Ecoregion",
    "Natural landscape",
    "Love",
    "Calendar",
    "Scrapbooking",
    "Shelf",
    "Shelving",
    "Retail",
    "Games",
    "Communication Device",
    "Water",
    "Decapoda",
    "Wing",
    "Waste containment",
    "Ear",
    "Distilled beverage",
    "Vehicle door",
    "Breastplate",
    "Armour",
    "Action film",
    "Costume",
    "Commemorative plaque",
    "Cutlery",
    "Top",
    "Marines",
    "Camouflage",
    "Cargo pants",
    "Machine gun",
    "Flag",
    "Aircraft",
    "Tattoo",
    "Necklace",
    "Jewellery",
    "Art book",
    "Thumbs signal",
    "Pleased",
    "Astronomical object",
    "Elephant",
    "Big cats",
    "House",
    "Beauty",
    "Glove",
    "Wine glass",
    "Child art",
    "Craft",
    "Needlework",
    "Scarecrow",
    "Artwork",
    "Ball",
    "Kit car",
    "Vehicle registration plate",
    "Gadget",
    "Fire",
    "Pet supply",
    "Dog collar",
    "Cooking",
    "Plastic bottle",
    "Carbonated soft drinks",
    "Stained glass",
    "Cuisine",
    "Dish",
    "Junk food",
    "Musical instrument accessory",
    "Transport",
    "Street light",
    "Groundcover",
    "Fedora",
    "Muscle",
    "Interaction",
    "Lipstick",
    "Photographer",
    "Camera lens",
    "Reflex camera",
    "Digital camera",
    "Camera",
    "Point-and-shoot camera",
    "Cameras & optics",
    "Plywood",
    "Natural material",
    "Rainbow",
    "Meteorological phenomenon",
    "Barechested",
    "Denim",
    "Skyscraper",
    "Monument",
    "Tower block",
    "Plastic bag",
    "Comfort food",
    "Footwear",
    "Rebellion",
    "Floor",
    "Cut flowers",
    "Diagram",
    "Traffic sign",
    "Fashion design",
    "Shadow",
    "Star",
    "Roar",
    "Indian elephant",
    "Elephants and Mammoths",
    "African elephant",
    "Violin family",
    "Sketch",
    "Stain",
    "Conversation",
    "Sketch pad",
    "Dinosaur",
    "Typesetting",
    "Electricity",
    "Octopus",
    "Cephalopod",
    "Feather",
    "Galliformes",
    "Phasianidae",
    "Chicken",
    "Fender",
    "Winter",
    "Freezing",
    "Uniform",
    "Butterfly",
    "signaling device",
    "Trigger",
    "Hulk",
    "Fluid",
    "Plumbing fixture",
    "Masque",
    "Mask",
    "Tradition",
    "Twig",
    "Soccer",
    "Player",
    "Sports uniform",
    "Football",
    "Protest",
    "Tank",
    "Self-propelled artillery",
    "Mode of transport",
    "Clown",
    "Limestone",
    "Rock",
    "Baseball cap",
    "Motif",
    "Christmas tree",
    "Christmas ornament",
    "Holiday ornament",
    "Ornament",
    "Christmas decoration",
    "Evergreen",
    "Peaked cap",
    "Fin",
    "Geology",
    "Movie",
    "Sport venue",
    "Military officer",
    "Interior design",
    "Joker",
    "Cg artwork",
    "Transparency",
    "Wax",
    "Pedestrian",
    "Memorial",
    "Songbird",
    "Airplane",
    "Aviation",
    "Air travel",
    "Helicopter",
    "Aerospace manufacturer",
    "Atmospheric phenomenon",
    "Makeover",
    "Triceratops",
    "Vegetable",
    "Nature reserve",
    "Oval",
    "Luggage and bags",
    "Seafood",
    "Button",
    "Close-up",
    "Automotive parking light",
    "Truck",
    "Ballistic vest",
    "Spokesperson",
    "Bear",
    "True frog",
    "Black cat",
    "Suidae",
    "Cosmetics",
    "Solution",
    "Sign language",
    "Lifebuoy",
    "Flag of the united states",
    "Flag Day (USA)",
    "Underpants",
    "Swimwear",
    "Address sign",
    "Banknote",
    "Money",
    "Currency",
    "Watch",
    "Clock",
    "Zombie",
    "Crane",
    "Public utility",
    "Overhead power line",
    "Electrical supply",
    "Wire",
    "Flame",
    "Sleeveless shirt",
    "Branch",
    "Serveware",
    "Tableware",
    "Carton",
    "Tourism",
    "Midnight",
    "Mast",
    "Electronic signage",
    "Birdhouse",
    "Plastic",
    "Dress shirt",
    "Display case",
    "Gunfighter",
    "Whiteboard",
    "Rabbit",
    "Rabbits and Hares",
    "Statue",
    "Candy cane",
    "Motorcycle",
    "Synthetic rubber",
    "Drum",
    "Bull",
    "Woody plant",
    "Flowering plant",
    "Decoration",
    "Smiley",
    "Souvenir",
    "Smoke",
    "Pollution",
    "Hearth",
    "Wood stain",
    "Staple food",
    "Varnish",
    "Automotive tail & brake light",
    "Mechanical fan",
    "Mario",
    "Flightless bird",
    "Palm tree",
    "Letter",
    "Nature",
    "Natural environment",
    "Primate",
    "Bat",
    "Coffee",
    "Greeting card",
    "Speed limit",
    "Canidae",
    "Visual effect lighting",
    "Neon",
    "Tablecloth",
    "Pole",
    "Costume design",
    "Youth",
    "Wind",
    "Nativity scene",
    "Comedy",
    "Web page",
    "Dobermann",
    "Software",
    "Crown",
    "Brown bear",
    "Membranophone",
    "Mesh",
    "Street artist",
    "Cricket cap",
    "Greeting",
    "Stage equipment",
    "Horn",
    "Bicycles--Equipment and supplies",
    "Grille",
    "Wool",
    "Stuffed toy",
    "Clothing",
    "Shoulder",
    "Trunks",
    "Walking shoe",
    "Baby & toddler clothing",
    "Child",
    "Pop music",
    "Food",
    "Fast food",
    "Cable",
    "Summer",
    "Belt",
    "Scarf",
    "Map",
    "Headstone",
    "Snow",
    "Grass family",
    "Garden tool",
    "Bull shark",
    "Windshield",
    "Electric guitar",
    "Military aircraft",
    "Stage",
    "Alpaca",
    "Llama",
    "Parking",
    "Gun accessory",
    "Transparent material",
    "Jacket",
    "Livestock",
    "Cash",
    "Money handling",
    "Rocket",
    "Fireworks",
    "Portable communications device",
    "Mobile device",
    "Holiday",
    "Modern art",
    "Moka pot",
    "Cone",
    "Beverage can",
    "Metropolitan area",
    "Animation",
    "Comfort",
    "Diving mask",
    "Brassiere",
    "Trademark",
    "Arecales",
    "Plant stem",
    "Table",
    "Beer bottle",
    "Meditation",
    "Fish",
    "Brain",
    "Display board",
    "Skateboard truck",
    "Manhole cover",
    "Clip art",
    "Stadium",
    "Idiophone",
];

export default labelsTable;
