const objectsTable = [
    "Packaged goods",
    "Poster",
    "Person",
    "Pants",
    "Animal",
    "Luggage & bags",
    "Hat",
    "Footwear",
    "Clothing",
    "Glasses",
    "Sunglasses",
    "Door",
    "Sun hat",
    "Shoe",
    "Guitar",
    "Racket",
    "Belt",
    "Helmet",
    "Scarf",
    "Whiteboard",
    "2D barcode",
    "Painting",
    "Pillow",
    "Lighting",
    "Bracelet",
    "Stop sign",
    "Picture frame",
    "Furniture",
    "Squash",
    "Toy",
    "Outerwear",
    "Tie",
    "1D barcode",
    "Car",
    "Top",
    "Suit",
    "Mirror",
    "Tableware",
    "Bag",
    "Building",
    "Bird",
    "Coat",
    "Insect",
    "Dress",
    "Moths and butterflies",
    "Swimwear",
    "Food",
    "Window",
    "License plate",
    "Goggles",
    "Sculpture",
    "Helicopter",
    "Train",
    "Bottled and jarred packaged goods",
    "Necklace",
    "Grooming trimmer",
    "Shorts",
    "Drink",
    "Envelope",
    "Bowtie",
    "Snowboard",
    "Jeans",
    "Tubed packaged goods",
    "Clock",
    "Single-lens reflex camera",
    "Camera",
    "Dog",
    "Bagged packaged goods",
    "Skirt",
    "Flag",
    "Light fixture",
    "Bottle",
    "Glove",
    "Chicken",
    "Flowerpot",
    "Wheel",
    "Boot",
    "Cat",
    "Tank",
    "Mouse",
    "Canned packaged goods",
    "Box",
    "Ball",
    "Tire",
    "Backpack",
    "Motorcycle",
    "Turtle",
    "Bicycle",
    "Door handle",
    "Table",
    "Van",
    "Home appliance",
    "Jacket",
    "Sock",
    "Plant",
    "Table top",
    "Boxed packaged goods",
    "Vinyl record",
    "Container",
    "Watch",
    "Baked goods",
    "Brassiere",
    "Spider",
    "Wheelchair",
    "Traffic sign",
    "Fork",
    "Flower",
];

export default objectsTable;
